timezone:          India/Kolakata

# Dependencies
markdown:         kramdown
highlighter:      pygments

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# Permalinks
permalink:        pretty

# Setup
title:            vchr0mbi3's Diary
tagline:          'Make it happen.'
description:      'Optimist | Foodie | Techie'
funkyline:        “I would love to change the world, but they won’t give me the source code. :P"

url:              "http://vchrombie.github.io"
baseurl:          "/blog"

disqus_shortname: vchrombie

author:
  name:           'Venu'
  url:            https://vchrombie.github.io/

paginate:         10

plugins:          [jekyll-paginate]


# Custom vars
appname:          blog
version:          2.1.0

github:
  repo:           https://github.com/vchrombie/blog/


# Site Owner configuration

owner:
  name: Venu Vardhan Reddy Tekula
  avatar: avatar.jpg
  job: "Optimist|Foodie|Techie"
  bio: "Sophomore from Amrita University, Amritapuri."
  email: venuvardhanreddytekula8@gmail.com
  disqus-shortname: vchrombie
  twitter: vchrombie #username
  facebook: vchrombie #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: vchrombie #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin:  #username
  xing: #username
  instagram: vchrombie #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
