#
###################################
# Site wide configuration
####################################
#

title: vchr0mbi3 Diary
email: venuvardhanreddytekula8@gmail.com
description: A simple and awesome blog theme powered by jekyll.
url: https://vchrombie.github.io/blog/ # the base hostname & protocol for your site
keywords: ["Programming"]

#
###################################
# Jekyll configuration
####################################
#

timezone:          India/Kolakata
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#

owner:
  name: Venu Vardhan Reddy Tekula
  avatar: avatar.jpg
  job: "Optimist|Foodie|Techie"
  bio: "Sophomore from Amrita University, Amritapuri."
  email: venuvardhanreddytekula8@gmail.com
  disqus-shortname: vchrombie
  twitter: vchrombie #username
  facebook: vchrombie #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: vchrombie #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: renyuan-zou-69b7038a #username
  xing: #username
  instagram: vchrombie #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
